/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogReport.java
 *
 * Created on Jun 17, 2010, 6:20:10 PM
 */

package timekeeper;
import java.util.ArrayList;

/**
 *
 * @author E0051024
 */
public class LogReport extends javax.swing.JFrame {
    private ArrayList logbook;
    private boolean loadedRecord;
    private java.util.Calendar loadDate;

    /** Creates new form LogReport */
    public LogReport(ArrayList logbook) {
        initComponents();
        this.logbook = logbook;
        //populateLog();
    }

    public LogReport(){
        initComponents();

    }

    public void setLoadedRecord(boolean state)
    {
        this.loadedRecord = state;
    }

    public void setLoadDate(java.util.Calendar load)
    {
        this.loadDate = (java.util.Calendar)load.clone();
    }

    public void clearLog(ArrayList logbook){
        this.logbook = logbook;
        this.loadedRecord = false;
        epResults.setText("Log for: " +
                java.util.Calendar.getInstance().getTime().toString() + "\n");
    }

    public void populateLog(){
        String results="";
        for(int i=0;i<logbook.size();i++)
        {
            results += logbook.get(i).toString() + "\n";
        }

        if(loadedRecord)
        {
            epResults.setText("Loaded Log from: " +
                this.loadDate.getTime().toString() + "\n" + results);
        }else
        {
            epResults.setText("Log for: " +
                java.util.Calendar.getInstance().getTime().toString() + "\n" + results);
        }

    }

    public void populateLog(ArrayList logbook)
    {
        this.logbook = logbook;
                String results="";
        for(int i=0;i<logbook.size();i++)
        {
            results += logbook.get(i).toString() + "\n";
        }

        if(loadedRecord)
        {
            epResults.setText("Loaded Log from: " +
                this.loadDate.getTime().toString() + "\n" + results);
        }else
        {
            epResults.setText("Log for: " +
                java.util.Calendar.getInstance().getTime().toString() + "\n" + results);
        }
        this.repaint();
        this.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        epResults = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TimeKeeper - Logbook");

        epResults.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(epResults);

        jLabel1.setText("Log Book Results");

        bClose.setText("Close");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 431, Short.MAX_VALUE)
                        .addComponent(bClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JEditorPane epResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
