/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsForm.java
 *
 * Created on Oct 22, 2009, 2:53:20 PM
 */

package timekeeper;
import java.io.*;
import java.util.Scanner;
import javax.swing.*;

/**
 *
 * @author James M. Olson
 */
public class SettingsForm extends javax.swing.JFrame {

    private String dbLocation;
    private String progLocation;
    private String exportLocation;
    private String reportLocation;
    private String defaultView;
    private String dbFilename;
    private String user;
    private String manager;
    private String[] defaultOracle;
    private String[] setOracle;
    private boolean failedStart;
    private boolean isInitialized;

    /** Creates new SettingsForm Instance to pass setting info only */
    public SettingsForm() {
        this.dbFilename = "\\TE.mdb";
        this.manager = "";
        this.user = "";
        this.failedStart = false;
        this.setOracle = new String[6];
        this.isInitialized = false;
        this.defaultOracle = new String[6];
        this.defaultOracle[0] = "###############################,";
        this.defaultOracle[1] = "ORACLE RESERVED SECTION,";
        this.defaultOracle[2] = "###############################,";
        this.defaultOracle[3] = "START_ORACLE,";
        this.defaultOracle[4] = "A|PROJECTS|Attribute1|A|PROJECTS|Attribute2|AE|PROJECTS|Attribute3"+
                "|PROJECTS|Attribute5|D|DI|CommentText|D|DI|CommentText|D|DI|"+
                "CommentText|D|DI|CommentText|D|DI|CommentText|D|DI|CommentText"+
                "|D|DI|CommentText|,2121472,DI|CommentText|,";
        this.defaultOracle[5] = "STOP_ORACLE,END";
        //try setup. if fails make new ini file and try again
        if(!setup()){
            makeNewIni();
            setup();
        }

    }

    /**Creates SettingsForm Form view*/
    public void initializeView(){
        initComponents();
        
        this.fc.setCurrentDirectory(new java.io.File("."));
        this.fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        this.fc.setAcceptAllFileFilterUsed(false);
        this.bApply.setEnabled(false);
        this.tbDatabaseLocation.setText(this.dbLocation);
        this.tbExportLocation.setText(this.exportLocation);
        this.tbReportLocation.setText(this.reportLocation);
        this.tbUser.setText(this.user);
        this.tbManager.setText(this.manager);
        if(this.defaultView.equalsIgnoreCase("Calendar"))
            this.rbCalendarView.setSelected(true);
        else
            this.rbTimeCardView.setSelected(true);

        this.taOracle.setText(this.setOracle[0]+"\n"+this.setOracle[1]+"\n"+
            this.setOracle[2]+"\n"+this.setOracle[3]+"\n"+
            this.setOracle[4]+"\n"+this.setOracle[5]);
        this.isInitialized = true;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        bgDefaultView = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbExportLocation = new javax.swing.JTextField();
        tbDatabaseLocation = new javax.swing.JTextField();
        bSetExportLoc = new javax.swing.JButton();
        bSetDBLoc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tbReportLocation = new javax.swing.JTextField();
        bSetReportLoc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taOracle = new javax.swing.JTextArea();
        bOracleDefault = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        bClose = new javax.swing.JButton();
        bApply = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        rbCalendarView = new javax.swing.JRadioButton();
        rbTimeCardView = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbManager = new javax.swing.JTextField();
        tbUser = new javax.swing.JTextField();
        bSetUser = new javax.swing.JButton();
        bSetMgr = new javax.swing.JButton();

        fc.setAcceptAllFileFilterUsed(false);
        fc.setApproveButtonText("Select");
        fc.setDialogTitle("TEWIN - Select Target Path");
        fc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Time Entry Settings");
        setLocationByPlatform(true);
        setName("SettingsForm"); // NOI18N

        jLabel2.setText("Time Card Export Location");

        jLabel3.setText("Database Location");

        tbExportLocation.setToolTipText("Location program will export time cards when EXPORT button is clicked");
        tbExportLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExportLocationActionPerformed(evt);
            }
        });

        tbDatabaseLocation.setToolTipText("Location main database is being stored");
        tbDatabaseLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDatabaseLocationActionPerformed(evt);
            }
        });

        bSetExportLoc.setText("SELECT");
        bSetExportLoc.setToolTipText("Open directory chooser for Time Card Export Location");
        bSetExportLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetExportLocActionPerformed(evt);
            }
        });

        bSetDBLoc.setText("SELECT");
        bSetDBLoc.setToolTipText("Open directory chooser for Database Location");
        bSetDBLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetDBLocActionPerformed(evt);
            }
        });

        jLabel6.setText("Report Save Location");

        tbReportLocation.setToolTipText("Location Database searches and report will be saved");
        tbReportLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbReportLocationActionPerformed(evt);
            }
        });

        bSetReportLoc.setText("SELECT");
        bSetReportLoc.setToolTipText("Open Directory Chooser for Report Save Location");
        bSetReportLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetReportLocActionPerformed(evt);
            }
        });

        jLabel1.setText("Oracle Suffix");

        taOracle.setColumns(20);
        taOracle.setRows(3);
        taOracle.setToolTipText("Oracle suffix added to bottom of Time Card export file");
        taOracle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taOracleKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(taOracle);

        bOracleDefault.setText("Set Oracle Suffix  to Default Value");
        bOracleDefault.setToolTipText("Set Oracle Suffix to default value");
        bOracleDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOracleDefaultActionPerformed(evt);
            }
        });

        bClose.setText("Close");
        bClose.setToolTipText("Close form and return to main applicaiton");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        bApply.setText("Apply");
        bApply.setToolTipText("Apply Changes to Settings");
        bApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApplyActionPerformed(evt);
            }
        });

        jLabel7.setText("Default View:");

        bgDefaultView.add(rbCalendarView);
        rbCalendarView.setSelected(true);
        rbCalendarView.setText("Calendar View");
        rbCalendarView.setToolTipText("Select Calendar View when program first loads");
        rbCalendarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCalendarViewActionPerformed(evt);
            }
        });

        bgDefaultView.add(rbTimeCardView);
        rbTimeCardView.setText("Weekly Time Card View");
        rbTimeCardView.setToolTipText("Select Time Card view to display when program loads");
        rbTimeCardView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTimeCardViewActionPerformed(evt);
            }
        });

        jLabel4.setText("User Name (as appears in Outlook) :");

        jLabel5.setText("Manager Name (as appears in Outlook) :");

        bSetUser.setText("SET");
        bSetUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetUserActionPerformed(evt);
            }
        });

        bSetMgr.setText("SET");
        bSetMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetMgrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 678, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tbDatabaseLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                                            .addComponent(tbExportLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                                            .addComponent(tbReportLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bSetExportLoc)
                                            .addComponent(bSetDBLoc)
                                            .addComponent(bSetReportLoc)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bApply, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(rbCalendarView)
                        .addGap(81, 81, 81)
                        .addComponent(rbTimeCardView)
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bOracleDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbManager, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bSetMgr))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bSetUser)))
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tbExportLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSetExportLoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbDatabaseLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSetDBLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tbReportLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSetReportLoc))
                .addGap(13, 13, 13)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSetUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tbManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSetMgr))
                .addGap(27, 27, 27)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCalendarView)
                    .addComponent(rbTimeCardView)
                    .addComponent(jLabel7))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bOracleDefault)
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bClose, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(bApply, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSetExportLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetExportLocActionPerformed
        if(this.fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            this.tbExportLocation.setText(this.fc.getSelectedFile().toString());
            this.exportLocation = this.tbExportLocation.getText();
            this.bApply.setEnabled(true);
        }

    }//GEN-LAST:event_bSetExportLocActionPerformed

    private void bSetDBLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetDBLocActionPerformed
        if(this.fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            String location = this.fc.getSelectedFile().toString();
            File temp = new File(location + "\\TE.MDB");
            if(temp.exists()){
                this.tbDatabaseLocation.setText(location);
                this.dbLocation = this.tbDatabaseLocation.getText();
                this.bApply.setEnabled(true);

            }else
            {
                javax.swing.JOptionPane.showMessageDialog(this, "ERROR: TE.MDB Not found in\n" + location );
                this.bApply.setEnabled(false);
            }

        }
    }//GEN-LAST:event_bSetDBLocActionPerformed

    private void bSetReportLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetReportLocActionPerformed
        if(this.fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            this.tbReportLocation.setText(this.fc.getSelectedFile().toString());
            this.reportLocation = this.tbReportLocation.getText();
            this.bApply.setEnabled(true);
        }
    }//GEN-LAST:event_bSetReportLocActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        if(this.failedStart){
            this.dispose();
            System.exit(0);
        }else
            this.dispose();
    }//GEN-LAST:event_bCloseActionPerformed

    private void bApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApplyActionPerformed
        
        File init = new File(this.progLocation + "\\TE.INI");

        try{
            BufferedWriter writer = new BufferedWriter(new FileWriter(init));
            writer.write("[TIMECARD_PATH]=" + this.exportLocation);
            writer.newLine();
            writer.write("[DB_PATH]=" + this.dbLocation);
            writer.newLine();
            writer.write("[REPORT_PATH]=" + this.reportLocation);
            writer.newLine();
            writer.write("[DEFAULT_VIEW]=" + this.defaultView);
            writer.newLine();
            writer.write("[USER]=" + this.user);
            writer.newLine();
            writer.write("[MANAGER]=" + this.manager);
            writer.newLine();
            writer.write("[ORACLE_START]");
            writer.newLine();
            writer.write(this.setOracle[0]);
            writer.newLine();
            writer.write(this.setOracle[1]);
            writer.newLine();
            writer.write(this.setOracle[2]);
            writer.newLine();
            writer.write(this.setOracle[3]);
            writer.newLine();
            writer.write(this.setOracle[4]);
            writer.newLine();
            writer.write(this.setOracle[5]);
            writer.newLine();
            writer.write("[ORACLE_END]");

            writer.close();


            this.bApply.setEnabled(false);
        }catch(Exception e) {
            e.printStackTrace();
        }   
    }//GEN-LAST:event_bApplyActionPerformed

    private void bOracleDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOracleDefaultActionPerformed

        this.taOracle.setText(this.defaultOracle[0]+"\n"+this.defaultOracle[1]+"\n"+
                this.defaultOracle[2]+"\n"+this.defaultOracle[3]+"\n"+
                this.defaultOracle[4]+"\n"+this.defaultOracle[5]);
        this.setOracle = this.defaultOracle;
        this.bApply.setEnabled(true);

    }//GEN-LAST:event_bOracleDefaultActionPerformed

    private void fcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcActionPerformed

   
    }//GEN-LAST:event_fcActionPerformed

    private void tbExportLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExportLocationActionPerformed

        this.bApply.setEnabled(true);
    }//GEN-LAST:event_tbExportLocationActionPerformed

    private void tbDatabaseLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDatabaseLocationActionPerformed

        this.bApply.setEnabled(true);
    }//GEN-LAST:event_tbDatabaseLocationActionPerformed

    private void tbReportLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbReportLocationActionPerformed

        this.bApply.setEnabled(true);
    }//GEN-LAST:event_tbReportLocationActionPerformed

    private void rbCalendarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCalendarViewActionPerformed

        this.bApply.setEnabled(true);
        this.defaultView = "Calendar";
    }//GEN-LAST:event_rbCalendarViewActionPerformed

    private void rbTimeCardViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTimeCardViewActionPerformed

        this.bApply.setEnabled(true);
        this.defaultView = "TimeCard";
    }//GEN-LAST:event_rbTimeCardViewActionPerformed

    private void taOracleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taOracleKeyTyped

        this.bApply.setEnabled(true);
    }//GEN-LAST:event_taOracleKeyTyped

    private void bSetUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetUserActionPerformed
        this.user = this.tbUser.getText();
        this.bApply.setEnabled(true);
    }//GEN-LAST:event_bSetUserActionPerformed

    private void bSetMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetMgrActionPerformed
        this.manager = this.tbManager.getText();
        this.bApply.setEnabled(true);
    }//GEN-LAST:event_bSetMgrActionPerformed

    private boolean setup(){
        File dir1 = new File (".");

        String delims = "=";
        String phrase;
        int counter=0;

        try{
            this.progLocation = dir1.getCanonicalPath();
            File checkINI = new File(this.progLocation + "\\TE.INI");
            if(!checkINI.exists()){
                JOptionPane.showMessageDialog(this, "Unable to locate the TE.INI File."+
                        "File must be int the same directory as the TEWIN.JAR Program");
                return false;
            }

        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error has occured in the Settings Class: " + e);
            e.printStackTrace();
            this.dispose();
        }


        try {
            Scanner s = null;
            try {
                s = new Scanner(new BufferedReader(new FileReader(dir1.getCanonicalPath() + "\\TE.INI")));
                boolean getOracle = false;
                int i = 0;

                while (s.hasNextLine()) {
                    phrase = s.nextLine();
                    if(counter <=5 && getOracle==false){
                        String[] tokens = phrase.split(delims);
                        switch(counter){
                           case 0:
                               if(tokens[1]!=null)
                                    this.exportLocation = tokens[1];
                               else
                                   this.exportLocation = "";
                               break;
                           case 1:
                               if(tokens[1]!=null)
                                    this.dbLocation = tokens[1];
                               else
                                   this.dbLocation = "";
                                break;
                            case 2:
                                if(tokens[1]!=null)
                                    this.reportLocation = tokens[1];
                                else
                                    this.reportLocation = "";
                                break;
                            case 3:
                                if(tokens[1]!=null)
                                    this.defaultView = tokens[1];
                                else
                                    this.defaultView = "Calendar";
                                break;
                            case 4:
                                if(tokens[1]!=null)
                                    this.user = tokens[1];
                                else
                                    this.user = "";
                                break;
                            case 5:
                                if(tokens[1]!=null)
                                    this.manager = tokens[1];
                                else
                                    this.manager = "";
                                break;
                            default:
                                break;
                        }
                        counter++;
                    }
                    if(getOracle)
                    {
                        if(phrase.equalsIgnoreCase("[ORACLE_END]"))
                            getOracle = false;
                        else
                            this.setOracle[i++] = phrase;
                    }

                    if (phrase.equalsIgnoreCase("[ORACLE_START]"))
                    {
                        getOracle = true;
                    }
                }
            } finally {
                if (s != null) {
                    s.close();
                }
            }
            
            
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        return true;

    }

    public String getDBFile(){
        return (this.dbLocation + this.dbFilename);
    }

    public String getDBLoation(){
        return this.dbLocation;
    }

    public String getExportLocation(){
        return this.exportLocation;
    }

    public String getReportLocation(){
        return this.reportLocation;
    }

    public String[] getOracleSuffix(){
        return this.setOracle;
    }

    public String getProgramLocation(){
        return this.progLocation;
    }

    public String getDefaultView(){
        return this.defaultView;
    }

    public String getManager(){
        return this.manager;

    }

    public String getUser()
    {
        return this.user;
    }

    public void failedStart(){
        File dir1 = new File (".");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        try
        {
            this.progLocation = dir1.getCanonicalPath();
            this.dbLocation = this.progLocation;
            this.exportLocation = this.progLocation;
            this.reportLocation = this.progLocation;
            this.tbDatabaseLocation.setText(this.progLocation);
            this.tbExportLocation.setText(this.progLocation);
            this.tbReportLocation.setText(this.progLocation);
            this.tbUser.setText("");
            this.tbManager.setText("");
            this.defaultView = "Calendar";
            this.taOracle.setText(this.defaultOracle[0]+ "\n" +
                    this.defaultOracle[1] + "\n" + this.defaultOracle[2] + "\n" +
                    this.defaultOracle[3] + "\n" + this.defaultOracle[4]);
            this.setOracle = this.defaultOracle;
            this.bApply.setEnabled(true);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        this.failedStart = true;

    }

    public boolean isInitialized(){
        return this.isInitialized;
    }


    private void makeNewIni(){
        File init = new File(this.progLocation + "\\TE.INI");
        

        try{
            init.createNewFile();
            BufferedWriter writer = new BufferedWriter(new FileWriter(init));
            writer.write("[TIMECARD_PATH]=" + this.progLocation);
            writer.newLine();
            writer.write("[DB_PATH]=" + this.progLocation);
            writer.newLine();
            writer.write("[REPORT_PATH]=" + this.progLocation);
            writer.newLine();
            writer.write("[DEFAULT_VIEW]=" + "Calendar");
            writer.newLine();
            writer.write("[USER]=" + " ");
            writer.newLine();
            writer.write("[MANAGER]=" + " ");
            writer.newLine();
            writer.write("[ORACLE_START]");
            writer.newLine();
            writer.write(this.defaultOracle[0]);
            writer.newLine();
            writer.write(this.defaultOracle[1]);
            writer.newLine();
            writer.write(this.defaultOracle[2]);
            writer.newLine();
            writer.write(this.defaultOracle[3]);
            writer.newLine();
            writer.write(this.defaultOracle[4]);
            writer.newLine();
            writer.write(this.defaultOracle[5]);
            writer.newLine();
            writer.write("[ORACLE_END]");
            writer.close();

        }catch(Exception e) {
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApply;
    private javax.swing.JButton bClose;
    private javax.swing.JButton bOracleDefault;
    private javax.swing.JButton bSetDBLoc;
    private javax.swing.JButton bSetExportLoc;
    private javax.swing.JButton bSetMgr;
    private javax.swing.JButton bSetReportLoc;
    private javax.swing.JButton bSetUser;
    private javax.swing.ButtonGroup bgDefaultView;
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JRadioButton rbCalendarView;
    private javax.swing.JRadioButton rbTimeCardView;
    private javax.swing.JTextArea taOracle;
    private javax.swing.JTextField tbDatabaseLocation;
    private javax.swing.JTextField tbExportLocation;
    private javax.swing.JTextField tbManager;
    private javax.swing.JTextField tbReportLocation;
    private javax.swing.JTextField tbUser;
    // End of variables declaration//GEN-END:variables


}
